# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.pre_1d_l1 <- function(ycoords, weights, error, decreasing = FALSE) {
    .Call('_PrefixRegression_pre_1d_l1', PACKAGE = 'PrefixRegression', ycoords, weights, error, decreasing)
}

.uni_1d_l1 <- function(ycoords, weights) {
    .Call('_PrefixRegression_uni_1d_l1', PACKAGE = 'PrefixRegression', ycoords, weights)
}

.pre_1d_l2 <- function(y_vec, w_vec, decreasing = FALSE) {
    .Call('_PrefixRegression_pre_1d_l2', PACKAGE = 'PrefixRegression', y_vec, w_vec, decreasing)
}

.uni_1d_l2 <- function(y_vec, w_vec) {
    .Call('_PrefixRegression_uni_1d_l2', PACKAGE = 'PrefixRegression', y_vec, w_vec)
}

.pre_1d_linf <- function(y, decreasing = FALSE) {
    .Call('_PrefixRegression_pre_1d_linf', PACKAGE = 'PrefixRegression', y, decreasing)
}

.uni_1d_linf <- function(y_vec) {
    .Call('_PrefixRegression_uni_1d_linf', PACKAGE = 'PrefixRegression', y_vec)
}

.pre_2d_l1_inc <- function(w, data) {
    .Call('_PrefixRegression_pre_2d_l1_inc', PACKAGE = 'PrefixRegression', w, data)
}

.pre_2d_l1_inc <- function(w, data) {
    .Call('_PrefixRegression_pre_2d_l2_inc', PACKAGE = 'PrefixRegression', w, data)
}

pre_1d <- function(y_vec, w_vec, metric, unimodal = FALSE, decreasing = FALSE) {
    .Call('_PrefixRegression_pre_1d', PACKAGE = 'PrefixRegression', y_vec, w_vec, metric, unimodal, decreasing)
}

pre_2d_increasing <- function(y_vec, w_vec, metric) {
    .Call('_PrefixRegression_pre_2d_increasing', PACKAGE = 'PrefixRegression', y_vec, w_vec, metric)
}

